[pytest]

markers =
    unit: fast tests for isolated functions/classes
    integration: tests using configs, datasets, or multiple components
    genetic: tests for genetic algorithm
    maripower: tests that need maripower support
    manual: tests that produce figures as output
addopts = -ra --tb=short --strict-markers
