[pytest]

markers = 
    genetic: tests for genetic algorithm
    maripower: tests that need maripower support
    manual: tests that produce figures as output
    regression: regression test
addopts = -ra --tb=short --strict-markers -m "not regression and not manual"



	
