name: Linting and pytests

on:
   push:
     branches:
       - 'main'

   pull_request:
     branches:
       - 'main'

   workflow_dispatch:

jobs:
  lint:

    runs-on: ubuntu-latest
    env:
      WRT_WEATHER_DATA: '${{ github.workspace }}/tests/data/reduced_testdata_weather.nc'
      WRT_DEPTH_DATA: '${{ github.workspace }}/tests/data/reduced_testdata_depth.nc'
      WRT_BASE_PATH: '${{ github.workspace }}'
      GL_TOKEN: '${{ secrets.GL_TOKEN }}'
    strategy:
      matrix:
        python-version: [ "3.9" ]
        #python-version: ["3.9", "3.10", "3.11"]

    steps:
      - uses: actions/checkout@v3
      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v4
        with:
          python-version: ${{ matrix.python-version }}
      - name: Install dependencies
        run: |
          # install dependencies required by cartopy
          sudo apt-get update && sudo apt-get -y install libproj-dev proj-data proj-bin libgeos-dev
          python -m pip install --upgrade pip
          if [ -f requirements.test.txt ]; then pip install -r requirements.test.txt; fi
          pip install git+https://git:${GL_TOKEN}@collaborating.tuhh.de/ces1314/maripower.git
      - name: Run flake8
        run: |
          flake8 --max-line-length=120  \
          --extend-ignore F401,F403,F405,E711
      - name: Run pytest
        run: |
          pytest tests
